volumes:
    v_wordpress:
        name: v_wordpress
        driver: local
        driver_opts:
            type: 'none'
            device: ${VOLUME_PATH}/wordpress
            o: bind
    v_database:
        name: v_database
        driver: local
        driver_opts:
            type: 'none'
            device: ${VOLUME_PATH}/mariadb
            o: bind
    v_website:
        name: v_website
        driver: local
        driver_opts:
            type: 'none'
            device: ${VOLUME_PATH}/website
            o: bind
    v_adminer:
        name: v_adminer
        driver: local
        driver_opts:
            type: 'none'
            device: ${VOLUME_PATH}/adminer
            o: bind
    v_portainer:
        name: v_portainer
        driver: local
        driver_opts:
            type: 'none'
            device: "${VOLUME_PATH}/portainer"
            o: bind

services:
    nginx:
        container_name: nginx
        build: ./requirements/nginx
        restart: on-failure
        env_file: .env
        volumes:
          - v_wordpress:/var/www/html/
          - v_website:/var/www/website/
          - v_adminer:/var/www/adminer/
        depends_on:
            - wordpress
        ports:
            - "443:443"
            - "4444:80"
            - "4445:8080"
            - "9443:9443"
        networks:
            - network-wordpress
            - network-static-site
            - network-adminer
            - network-portainer
    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        restart: unless-stopped
        env_file: .env
        volumes:
            - v_database:/var/lib/mysql/
        networks:
            - network-ddb
    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress
        restart: on-failure
        env_file: .env
        volumes:
            - v_wordpress:/var/www/html/
        depends_on:
            - mariadb
        networks:
            - network-wordpress
            - network-ddb
    website:
        container_name: website
        build: ./requirements/bonus/website
        restart: on-failure
        # env_file: .env
        volumes:
            - v_website:/var/www/website/
        networks:
            - network-static-site
    adminer:
        container_name: adminer
        build: ./requirements/bonus/adminer
        restart: on-failure
        volumes:
            - v_adminer:/var/www/adminer/
        networks:
            - network-adminer
            - network-ddb
    portainer:
        container_name: portainer
        build: ./requirements/bonus/portainer
        restart: on-failure
        ports:
          - "4450:9443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - v_portainer:/data
        networks:
            - network-portainer
            - network-wordpress
            - network-ddb
            - network-static-site
            - network-adminer

networks:
    network-wordpress:
        driver: bridge
    network-ddb:
        driver: bridge
    network-static-site:
        driver: bridge
    network-adminer:
        driver: bridge
    network-portainer:
        driver: bridge
