volumes:
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            type: 'none'
            device: ../data/wordpress
            o: bind
    database:
        name: database
        driver: local
        driver_opts:
            type: 'none'
            device: ../data/mariadb
            o: bind
    website:
        name: website
        driver: local
        driver_opts:
            type: 'none'
            device: ../data/website
            o: bind

services:
    nginx:
        container_name: nginx
        build: ./requirements/nginx
        restart: on-failure
        env_file: .env
        volumes:
          - wordpress:/var/www/html/
          - website:/var/www/html/
        depends_on:
            - wordpress
        ports:
            - "4443:443"
            - "4444:80"
        networks:
            - network
    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        restart: unless-stopped
        env_file: .env
        volumes:
            - database:/var/lib/mysql/
        networks:
            - network
        expose:
            - 3306
    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress
        restart: on-failure
        env_file: .env
        volumes:
            - wordpress:/var/www/html/
        depends_on:
            - mariadb
        networks:
            - network
    website:
        container_name: website
        build: ./requirements/bonus/website
        restart: on-failure
        # env_file: .env
        volumes:
            - website:/var/www/html/
        networks:
            - network

networks:
    network:
        driver: bridge

